spring:
  batch:
    job:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: ${spring.jpa.database-platform}
      hibernate.format_sql: false
      hibernate.show_sql: false
      hibernate.jdbc.batch_size: 20
      hibernate.search.enabled: true
      hibernate.search.backend.type: lucene
      hibernate.search.backend.analysis.configurer: ca.uhn.fhir.jpa.search.HapiLuceneAnalysisConfigurer
      hibernate.search.backend.directory.type: local-filesystem
      hibernate.search.backend.directory.root: lucenefiles
      hibernate.search.backend.lucene_version: lucene_current
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.dao.PersistenceExceptionTranslationAutoConfiguration
      - org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchRestClientAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
