compass:
  certificate-template: "classpath:/report/certificate.pdf"
  codesystem-report-template: "classpath:/report/codesystems.pdf"
hapi:
  fhir:
    implementation-guides:
      gecco:
        name: de.gecco
        version: 1.0.4
    #remote-terminology-servers:
      #- "https://snowstorm-fhir.snomedtools.org/fhir"
      #- "https://tx.fhir.org/r4/"
      #- "https://fhir.loinc.org"
      #- "https://r4.ontoserver.csiro.au/fhir"
    # See the documentation on the required layout of the zip files
    #code-systems:
      #loinc: "/path/to/file.zip"
      #snomed: "/path/to/file.zip"
    code-systems:
      loinc: "/home/yannikw/MeDIC/Terminologien/Loinc_2.70.zip"
      snomed: "/home/yannikw/MeDIC/Terminologien/SnomedCT_InternationalRF2_PRODUCTION_20200309T120000Z.zip"
spring:
  batch:
    job:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: ${spring.jpa.database-platform}
      hibernate.format_sql: false
      hibernate.show_sql: false
      hibernate.jdbc.batch_size: 250
      hibernate.search.enabled: true
      hibernate.search.backend.type: lucene
      hibernate.search.backend.analysis.configurer: ca.uhn.fhir.jpa.search.HapiLuceneAnalysisConfigurer
      hibernate.search.backend.directory.type: local-filesystem
      hibernate.search.backend.directory.root: lucenefiles
      hibernate.search.backend.lucene_version: lucene_current
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.dao.PersistenceExceptionTranslationAutoConfiguration
      - org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchRestClientAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
