version: '3.8'

services:
  postgres:
    image: postgres:13.3
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  compass-conformance-server:
    image: ${CONFORMANCE_SERVER_IMAGE:-compass-conformance-server:0.0.1-SNAPSHOT}
    container_name: compass-conformance-server
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_USER:-postgres}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER:-postgres}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD:-changeme}
    # map external configuration  files
    #  - SPRING_CONFIG_LOCATION=/app/config
    #volumes:
    #  - "/path/to/config:/app/config"
    ports:
      - "8080:8080"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
